server:
  port: 8081
spring:
  application:
    name: sjt-test-producer
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/