server:
  port: 8087
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: hystrix_route
          uri: http://www.baidu.com
          predicates:
            - Path=/sjt
          filters:
            - Hystrix=myCommandName